# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version = 0.9.0
maven_group = com.fej1fun
mod_id = potentials
enabled_platforms = fabric,neoforge
release_type = beta
# alpha / beta / stable

# Minecraft properties
minecraft_version = 26.1.2
supported_minecraft_versions = { "versions": ["26.1", "26.1.1", "26.1.2"] }

# Dependencies
architectury_api_version = 20.0.5
fabric_loader_version = 0.19.3
fabric_api_version = 0.150.0+26.1.2
neoforge_version = 26.1.2.71
