# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version = 0.7.3
maven_group = com.fej1fun
archives_name = potentials
enabled_platforms = fabric,neoforge
release_type = alpha
# alpha / beta / stable

# Minecraft properties
minecraft_version = 1.21.9
supported_minecraft_versions = { "versions": ["1.21.9", "1.21.10"] }

# Dependencies
architectury_api_version = 16.1.4
fabric_loader_version = 0.17.3
fabric_api_version = 0.134.0+1.21.9
neoforge_version = 21.9.16-beta

fabric_energy_version = 4.2.0
