# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

# Mod properties
mod_version = 0.10.0
maven_group = com.fej1fun
mod_id = potentials
enabled_platforms = fabric,neoforge
release_type = beta
# alpha / beta / stable

# Minecraft properties
minecraft_version = 26.3
supported_minecraft_versions = { "versions": ["26.3"] }

# Dependencies
architectury_api_version = 22.0.4
fabric_loader_version = 0.19.5
fabric_api_version = 0.161.0+26.3
neoforge_version = 26.3.0.57-beta
