architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    developmentFabric.extendsFrom common
}

repositories {
    exclusiveContent {
        forRepository {
            maven { url "https://cursemaven.com" }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    include api('teamreborn:energy:5.0.0')

    implementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    implementation "net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version"
    implementation "dev.architectury:architectury-fabric:$rootProject.architectury_api_version"

    implementation project(path: ':fabric')
    common(project(path: ':common')) { transitive = false }
    common(project(path: ':test-common')) { transitive = false }
}
