modLoader = "javafml"
loaderVersion = "[10,)"
issueTrackerURL = "https://github.com/Fej1Dev/Potentials/issues"
license = "MIT"

[[mods]]
modId = "potentials"
version = "${version}"
displayName = "Potentials"
authors = "Fej1Fun"
description = '''Library to allow mod developers to use cross platform capabilities'''
iconFile = "assets/potentials/icon.png"

[[dependencies.potentials]]
modId = "neoforge"
type = "required"
versionRange = "[26.3.0.39-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.potentials]]
modId = "minecraft"
type = "required"
versionRange = "[26.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.potentials]]
modId = "architectury"
type = "required"
versionRange = "[22.0.3,)"
ordering = "AFTER"
side = "BOTH"