modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Fej1Dev/Potentials/issues"
license = "MIT"

[[mods]]
modId = "potentials"
version = "${version}"
displayName = "Potentials"
authors = "Fej1Fun"
description = '''Library to allow mod developers to use cross platform capabilities'''
#logoFile = ""

[[dependencies.potentials]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.potentials]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5, 1.21.6, 1.21.7, 1.21.8]"
ordering = "NONE"
side = "BOTH"

[[dependencies.potentials]]
modId = "architectury"
type = "required"
versionRange = "[16.0.3,)"
ordering = "AFTER"
side = "BOTH"