modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Fej1Dev/Potentials/issues"
license = "MIT"

[[mods]]
modId = "potentials"
version = "${version}"
displayName = "Potentials"
authors = "Fej1Fun"
description = '''''' #TODO fill the descriptions
#logoFile = ""

[[dependencies.potentials]]
modId = "neoforge"
type = "required"
versionRange = "[21.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.potentials]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.potentials]]
modId = "architectury"
type = "required"
versionRange = "[14.0.4,)"
ordering = "AFTER"
side = "BOTH"