modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Fej1Dev/Potentials/issues"
license = "Unlicense"

[[mods]]
modId = "potentials_test"
version = "1.0.0"
displayName = "Potentials Test"
authors = "Fej1Fun"
description = ''''''
#logoFile = ""

[[dependencies.potentials_test]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.potentials_test]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.3,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.potentials_test]]
modId = "architectury"
type = "required"
versionRange = "[14.0.4,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.potentials_test]]
modId = "potentials"
type = "required"
versionRange = "[0.6.0,)"
ordering = "AFTER"
side = "BOTH"
