modLoader = "javafml"
loaderVersion = "[10,)"
issueTrackerURL = "https://github.com/Fej1Dev/Potentials/issues"
license = "Unlicense"

[[mods]]
modId = "potentials_test"
version = "2.0.0"
displayName = "Potentials Test"
authors = "Fej1Fun"
description = ''''''
#logoFile = ""

[[dependencies.potentials_test]]
modId = "neoforge"
type = "required"
versionRange = "[21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.potentials_test]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.9,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.potentials_test]]
modId = "architectury"
type = "required"
versionRange = "[18.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.potentials_test]]
modId = "potentials"
type = "required"
versionRange = "[0.7.0,)"
ordering = "AFTER"
side = "BOTH"
